# Generated by Django 4.1.7 on 2023-03-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundphoto',
            options={'verbose_name': 'Фотка фона', 'verbose_name_plural': 'Фотки фона'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsphoto',
            options={'verbose_name': 'Фотка новости', 'verbose_name_plural': 'Фотка новости'},
        ),
    ]
