# Generated by Django 3.2.15 on 2023-07-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230621_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
